In [1]:
#start of numpy
#importing numpy
import numpy as np

In [29]:
arr1=np.arange(1000)
arr1

In [3]:
l1=list(range(1000))

In [30]:
#this is used to calculate time of any operation perform
%time arr1*2

In [5]:
arr2=np.random.randn(8)
arr2

array([-1.76175531,  1.13335387,  0.10426389,  0.84899988, -2.30022956,
       -1.30459076,  0.24851879, -0.4964458 ])

In [6]:
arr3=np.random.randint(6)
arr3
#random generated numbers have no shape and dimesion and no datatype

5

In [7]:
arr4=np.array([[1,2],[3,4]],dtype="float32")

In [8]:
print(arr4.shape)  #for finding row and column of array
print(arr4.ndim)   #find the dimension of array
print(arr4.dtype)  #find datatype of data in array

(2, 2)
2
float32


In [9]:
l=[[[1,2],[3,4]],[[5,6],[7,8]]]


In [10]:
arr5=np.array(l)
print(arr5.shape)
print(arr5.ndim)
print(arr5.dtype)
#print(arr5)

(2, 2, 2)
3
int32


In [11]:
arr6=np.zeros((2,3))


In [12]:
arr7=np.ones((2,2,2))
arr7

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [17]:
arr8=np.empty((2,3,2)) #empty take 0 or garbage values
arr8

array([[[6.23042070e-307, 3.56043053e-307],
        [1.60219306e-306, 7.56571288e-307],
        [1.89146896e-307, 1.37961302e-306]],

       [[1.05699242e-307, 8.01097889e-307],
        [1.78019082e-306, 1.29061414e-306],
        [2.22522596e-306, 0.00000000e+000]]])

In [27]:
arr9=np.asarray(arr6)
arr9

array([[0., 0., 0.],
       [0., 0., 0.]])

In [28]:
arr9=np.ones_like(arr6)
arr9

array([[1., 1., 1.],
       [1., 1., 1.]])

In [48]:
#Produce an array of the given shape and dtype with all values set to the 
arr10=np.full(2,3)
arr10

array([3, 3])

In [52]:
arr11=np.full_like(arr8,1)
#indicated “fill value” full_like takes another array and produces a filled
#array of the same shape and dtype
arr11

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [55]:
arr12=np.array([1,2,3],dtype=np.int32)
#another way to indicate datatype

In [57]:
arr12.astype(np.float32) # change datatype

array([1., 2., 3.], dtype=float32)

# Arithmetic with NumPy Arrays

In [62]:
arr12*2

array([2, 4, 6])

In [67]:
a1=np.array([1,2])
a2=np.array([[1,2],[3,4]])
a1+3


array([4, 5])

In [68]:
a1+a2

array([[2, 4],
       [4, 6]])

In [69]:
a1/2


array([0.5, 1. ])

In [70]:
a2*2

array([[2, 4],
       [6, 8]])

In [71]:
a2>a1

array([[False, False],
       [ True,  True]])

In [72]:
a1>a2

array([[False, False],
       [False, False]])

In [73]:
(a1+a2)>2

array([[False,  True],
       [ True,  True]])