In [3]:
import numpy as np

# slicing and indexing

In [2]:
arr=np.arange(6)
arr

array([0, 1, 2, 3, 4, 5])

In [3]:
arr[5]

5

In [4]:
arr[2:]

array([2, 3, 4, 5])

In [5]:
arr[[2]]

array([2])

In [22]:
arr1=np.array([[2,4],[3,6],[4,8]])

In [23]:
arr1[2]

array([4, 8])

In [38]:
arr1[0][1]  #use for 2d array slicing

4

In [39]:
arr1[1:,0]

array([3, 4])

In [18]:
arr1[0,1]   #use for 2d array slicing

4

In [33]:
arr2=np.array([[[1,1],[2,4],[3,9]],[[2,3],[3,4],[4,5]],[[2,8],[1,4],[4,7]]])   #use for 3d array slicing
arr2[1][2][0]

4

In [34]:
arr2[1,2,0]

4

In [35]:
arr2[1:]

array([[[2, 3],
        [3, 4],
        [4, 5]],

       [[2, 8],
        [1, 4],
        [4, 7]]])

In [36]:
arr2[1: ,0,1]

array([3, 8])

In [37]:
arr2[1,2,0]

4

In [40]:
arr2[0,0,0]=0

In [41]:
arr2

array([[[0, 1],
        [2, 4],
        [3, 9]],

       [[2, 3],
        [3, 4],
        [4, 5]],

       [[2, 8],
        [1, 4],
        [4, 7]]])

# BOOLEAN INDEXING

In [8]:
a=["ahil","arish","ali","adil","ahil","asim","adil","asim"]
names=np.array(a)


In [22]:
data=np.arange(8)

In [13]:
names=="ahil"   

array([ True, False, False, False,  True, False, False, False])

In [74]:
c= names=="ahil"

In [75]:
c

array([ True, False, False, False,  True, False, False, False])

In [73]:
data[names=='ahil']

array([0, 0])

In [23]:
data[names=='asim'] #use single comma and return value of the same index as asim

array([5, 7])

In [30]:
data[names=='ahil']=0

In [31]:
data  #value of data are modify

array([0, 1, 2, 3, 0, 5, 6, 7])

In [32]:
array=np.array([[1,2],[3,4],[5,6],[7,8],[0,1],[3,2],[4,7],[9,4]])

In [33]:
array[names!='adil',1]

array([2, 4, 6, 1, 2, 4])

In [50]:
L=np.array([1,2,4,1,6,2,7,2,3,2])

In [76]:
students=np.array(["salaar","maaz","saad","ali","saim","ibrahim","saad","arish","nabeel","zain"])

In [80]:
cond = (students=="saad") | (students=="saim")
cond

array([False, False,  True, False,  True, False,  True, False, False,
       False])

In [82]:
L[cond]

array([4, 6, 7])

In [83]:
L[~cond]  #return all values opposite to the condition

array([1, 2, 1, 2, 2, 3, 2])

# Transposing Arrays and Swapping Axes

In [97]:
array=np.array([1,2,3,4])
array

array([1, 2, 3, 4])

In [98]:
array.T

array([1, 2, 3, 4])

In [95]:
arr3=np.array([[1,2],[3,6],[4,8]])
arr3

array([[1, 2],
       [3, 6],
       [4, 8]])

In [94]:
arr3.T

array([[1, 3, 4],
       [2, 6, 8]])

In [99]:
np.dot(arr3.T, arr3)

array([[ 26,  52],
       [ 52, 104]])

In [110]:
arr4=np.array([[[8,2],[1,6],[9,8]],[[3,6],[3,7],[7,1]]])

In [111]:
arr4

array([[[8, 2],
        [1, 6],
        [9, 8]],

       [[3, 6],
        [3, 7],
        [7, 1]]])

In [114]:
arr4.swapaxes(1,2)

array([[[8, 1, 9],
        [2, 6, 8]],

       [[3, 3, 7],
        [6, 7, 1]]])